### PR TITLE
Homepage

### PR DESCRIPTION
**Pull request by principlebrothers**
### Complete milestone one: 
-  Setup header and footer navigation
-  Setup item list structure

### CODE REVIEW

**Review by bienvenuushindi — CHANGES_REQUESTED** [review]
# REQUIRED CHANGES 🔴

Hi, @principlebrothers, 

Good job so far!

There are some issues that you still need to work on before you merge your work 

## Highlights

- Great job setting up the correct linters ✔️
- Highly organized and clean code ✔️ 👨🏻‍💻
- Professional documentation ✔️
- Correct workflow ✔️
- Meaningful commit messages ✔️

## Required changes
- Please make sure you stick to  the design, Your page should look this :point_down: 
-

  Expected               |  Your Design
:-------------------------:|:-------------------------:
homepageErnest| homepageErnest


- Kindly Add the top navigation 
- Consider Implementing the navigation. I should be able to navigate to a new page if I click on an item in the bottom navigation

Cheers and Happy coding!👏👏👏

**Comment by principlebrothers** [comment]
Thanks for pointing that out @bienvenuushindi. I will work on it and submit it today

**Comment by principlebrothers** [comment]
Hello @bienvenuushindi, all requirement has been implemented. Kindly check and review.

**Review by bienvenuushindi — APPROVED** [review]
## Project Approved 🏆 🎉

Hi @principlebrothers 
Your project is complete! You have done it exceptionally well. it's time to merge it 💯
Congratulations! 🎉
### Highlight 👍
- Well implemented requirements.
- Kudos for the navigation
- No linter error

**Comment by principlebrothers** [comment]
Thanks for the review @bienvenuushindi

**Pull request merged**
